### ISSUE TITLE
Adjust color palette to change #d2d2d2 to something darker

### ISSUE THREAD

**Issue by emilykreimal** [UrbanInstitute/urban_R_theme#34]
It is too light to see clearly and also very similar to the panel grid lines (#DEDDDD)

**Comment by emilykreimal** [comment]
I think #5c5859 would be too similar to #000000 but #9d9d9d could be a good middle ground?

**Comment by bchartoff** [comment]
Hi @emilykreimal !

I agree that #d2d2d2 is tough to see as a thin line in a line chart (assuming that's where you're running into difficulties?). It's really intended as a color for bar or area charts, where the blocks of color are much more visible.

While it's not explicitly mentioned in Urban's [data viz style guide] (http://urbaninstitute.github.io/graphics-styleguide/) (yet! it's a constantly evolving doc), we often treat #d2d2d2 as a color that indicates "less important". So, if in a bar chart we wanted to highlight 4 of 20 bars, we'd color 4 #1696d2 and 16 #d2d2d2. [_As an aside, we often use #ec008b (pink) for the opposite purposes—to highlight a small number of elements (e.g. 1 bar in a distribution indicating "total". Too many pink elements look garish, but just a few really pop._]

Unfortunately we can't add #9d9d9d or any other colors to the categorical color palette, as the categorical colors are laid out explicitly in the above-linked style guide, and we strive for brand consistency across graphs and products. So that means, if you're concerned about legibility of line charts, you're really limited to five categorical colors. This doesn't mean you can't have more than 5 lines on a chart, but the style guide limits the number of categorical colors because after a certain point, they become very difficult to distinguish from each other. Various solutions could exist, including:

- Using the same color for all lines, or multiple lines, and directly labelling them on the graph
- Splitting the line chart up into multiple charts, placing them side by side, if necessary, on the same y scale, for easy comparison
- Curating the chart—removing lines which aren't necessary to the chart's narrative, or just add visual clutter
- Collapsing series together—summing or averaging multiple series to create an "Other" or similar series

Happy to chat more, either on this thread or offline. Thanks!

**Comment by emilykreimal** [comment]
@bchartoff understood! Thanks.
